package auth

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"io"
	"kiro-go/config"
	"net/http"
	"net/url"
	"strings"
	"testing"
)

type authRoundTripFunc func(*http.Request) (*http.Response, error)

func (fn authRoundTripFunc) RoundTrip(request *http.Request) (*http.Response, error) {
	return fn(request)
}

func TestExtractStartURLFromClientSecret(t *testing.T) {
	serialized := `{"initiateLoginUri":"https://d-1234567890.awsapps.com/start/"}`
	payload := `{"serialized":` + strconvQuote(serialized) + `}`
	secret := "header." + base64.RawURLEncoding.EncodeToString([]byte(payload)) + ".signature"

	if got := ExtractStartURLFromClientSecret(secret); got != "https://d-1234567890.awsapps.com/start" {
		t.Fatalf("unexpected extracted start URL: %q", got)
	}
	if IsBuilderIDStartURL(gotBuilderStartURL()) != true {
		t.Fatal("Builder ID start URL was not recognized")
	}
	if IsBuilderIDStartURL("https://d-1234567890.awsapps.com/start") {
		t.Fatal("enterprise start URL was classified as Builder ID")
	}
}

func TestExtractStartURLRejectsNonAWSURL(t *testing.T) {
	serialized := `{"initiateLoginUri":"https://example.com/start"}`
	payload := `{"serialized":` + strconvQuote(serialized) + `}`
	secret := "header." + base64.RawURLEncoding.EncodeToString([]byte(payload)) + ".signature"
	if got := ExtractStartURLFromClientSecret(secret); got != "" {
		t.Fatalf("non-AWS start URL should be rejected, got %q", got)
	}
}

func TestCompleteIamSsoLoginRetainsMetadata(t *testing.T) {
	client := &http.Client{Transport: authRoundTripFunc(func(request *http.Request) (*http.Response, error) {
		body := `{"clientId":"client-id","clientSecret":"client-secret"}`
		if request.URL.Path == "/token" {
			body = `{"accessToken":"access-token","refreshToken":"refresh-token","expiresIn":3600}`
		}
		return &http.Response{
			StatusCode: http.StatusOK,
			Body:       io.NopCloser(strings.NewReader(body)),
			Header:     make(http.Header),
		}, nil
	})}
	previous := SetGlobalAuthClientForTest(client)
	defer SetGlobalAuthClientForTest(previous)

	startURL := "https://tenant.awsapps.com/start/"
	sessionID, authorizeURL, _, err := StartIamSsoLogin(startURL, "eu-north-1")
	if err != nil {
		t.Fatalf("start IAM SSO: %v", err)
	}
	parsed, err := url.Parse(authorizeURL)
	if err != nil {
		t.Fatalf("parse authorize URL: %v", err)
	}
	callback := "http://127.0.0.1/oauth/callback?code=code&state=" + url.QueryEscape(parsed.Query().Get("state"))
	result, err := CompleteIamSsoLoginWithMetadata(sessionID, callback)
	if err != nil {
		t.Fatalf("complete IAM SSO: %v", err)
	}
	if result.Region != "eu-north-1" || result.StartURL != "https://tenant.awsapps.com/start" {
		t.Fatalf("IAM metadata was lost: %+v", result)
	}
	if result.AccessToken != "access-token" || result.RefreshToken != "refresh-token" {
		t.Fatalf("unexpected IAM tokens: %+v", result)
	}
}

func TestRefreshTokenClassifiesCloudFrontBlock(t *testing.T) {
	client := &http.Client{Transport: authRoundTripFunc(func(*http.Request) (*http.Response, error) {
		return &http.Response{
			StatusCode: http.StatusForbidden,
			Body: io.NopCloser(strings.NewReader(
				"<html>The request could not be satisfied. Request blocked. Generated by cloudfront</html>",
			)),
			Header: make(http.Header),
		}, nil
	})}
	previous := SetGlobalAuthClientForTest(client)
	defer SetGlobalAuthClientForTest(previous)

	_, _, _, _, err := RefreshToken(&config.Account{AuthMethod: "social", RefreshToken: "refresh"})
	if !errors.Is(err, ErrRefreshUpstreamBlocked) {
		t.Fatalf("expected shared upstream block, got %v", err)
	}
	if strings.Contains(err.Error(), "Generated by cloudfront") || strings.Contains(err.Error(), "403") {
		t.Fatalf("CloudFront body/status leaked into account-facing error: %v", err)
	}
}

func strconvQuote(value string) string {
	encoded, _ := json.Marshal(value)
	return string(encoded)
}

func gotBuilderStartURL() string {
	return "https://view.awsapps.com/start/"
}
