package proxy

import (
	"context"
	"io"
	"kiro-go/auth"
	"kiro-go/config"
	accountpool "kiro-go/pool"
	"net/http"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

func TestBackgroundRefreshCloudFrontBlockDoesNotCooldownAccounts(t *testing.T) {
	if err := config.Init(filepath.Join(t.TempDir(), "config.json")); err != nil {
		t.Fatalf("config.Init: %v", err)
	}
	sharedTokenRefreshCoordinator.mu.Lock()
	sharedTokenRefreshCoordinator.upstreamBlockedUntil = time.Time{}
	sharedTokenRefreshCoordinator.mu.Unlock()
	t.Cleanup(func() {
		sharedTokenRefreshCoordinator.mu.Lock()
		sharedTokenRefreshCoordinator.upstreamBlockedUntil = time.Time{}
		sharedTokenRefreshCoordinator.mu.Unlock()
	})

	var calls int32
	client := &http.Client{Transport: roundTripFunc(func(*http.Request) (*http.Response, error) {
		atomic.AddInt32(&calls, 1)
		return &http.Response{
			StatusCode: http.StatusForbidden,
			Body: io.NopCloser(strings.NewReader(
				"<html>The request could not be satisfied. Request blocked. Generated by cloudfront</html>",
			)),
			Header: make(http.Header),
		}, nil
	})}
	previousClient := auth.SetGlobalAuthClientForTest(client)
	defer auth.SetGlobalAuthClientForTest(previousClient)

	handler := &Handler{backgroundCtx: context.Background(), autoRefreshFail: make(map[string]int64)}
	settings := config.GetAutoRefreshConfig()
	first := handler.refreshOneAccount(&config.Account{
		ID: "cloudfront-a", Email: "a@example.com", Enabled: true,
		AuthMethod: "social", RefreshToken: "refresh-a",
	}, settings)
	second := handler.refreshOneAccount(&config.Account{
		ID: "cloudfront-b", Email: "b@example.com", Enabled: true,
		AuthMethod: "social", RefreshToken: "refresh-b",
	}, settings)

	for _, result := range []autoRefreshAccountResult{first, second} {
		if result.Status != "skipped" || result.CooldownUntil != 0 || !auth.IsRefreshUpstreamBlocked(result.Err) {
			t.Fatalf("shared block should skip without cooldown: %+v", result)
		}
	}
	if got := atomic.LoadInt32(&calls); got != 1 {
		t.Fatalf("global refresh block should suppress repeated calls, got %d", got)
	}
	if len(handler.autoRefreshFail) != 0 {
		t.Fatalf("CloudFront block created per-account cooldowns: %+v", handler.autoRefreshFail)
	}
	if accountpool.IsAuthFailure(first.Err) {
		t.Fatalf("shared CloudFront block was classified as revoked credentials: %v", first.Err)
	}
}
